#include "forge/commands/release.hpp"
#include "forge/core/process_runner.hpp"

#include <iostream>
#include <fstream>
#include <filesystem>
#include <string>
#include <vector>
#include <chrono>

#ifdef _WIN32
#include <windows.h>
#endif

namespace fs = std::filesystem;

namespace forge {

namespace {

void enableConsoleEncoding() {
#ifdef _WIN32
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (hOut != INVALID_HANDLE_VALUE) {
        DWORD dwMode = 0;
        if (GetConsoleMode(hOut, &dwMode)) {
            dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
            SetConsoleMode(hOut, dwMode);
        }
    }
#endif
}

void printReleaseHelp() {
    std::cout
        << "\n"
        << "Forge Release Packaging & Staging Engine\n\n"

        << "Usage:\n"
        << "  forge release <version> [options]\n\n"

        << "Options:\n"
        << "  -o, --output <dir>      Output base directory [default: dist/]\n"
        << "  --skip-build            Skip triggering CMake/Ninja release build\n"
        << "  -h, --help              Show this help message\n\n"

        << "Example:\n"
        << "  forge release v1.0.0\n";
}

} // anonymous namespace

int runRelease(int argc, char* argv[]) {
    enableConsoleEncoding();

    if (argc < 3) {
        printReleaseHelp();
        return 1;
    }

    std::string version;
    fs::path baseDistDir = "dist";
    bool skipBuild = false;

    for (int i = 2; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") {
            printReleaseHelp();
            return 0;
        } else if (arg == "--skip-build") {
            skipBuild = true;
        } else if ((arg == "-o" || arg == "--output") && i + 1 < argc) {
            baseDistDir = argv[++i];
        } else if (version.empty() && arg[0] != '-') {
            version = arg;
        }
    }

    if (version.empty()) {
        std::cerr << "  [!] Error: Release version string is required (e.g., v1.0.0).\n\n";
        return 1;
    }

    std::cout << "\nForge Release Packaging Engine\n";
    std::cout << "--------------------------------------------\n";
    std::cout << "  Release Tag   : " << version << "\n";

    fs::path releaseDir = baseDistDir / version;
    std::cout << "  Target Path   : " << releaseDir.string() << "\n\n";

    if (!skipBuild) {
        std::cout << "[1/4] Compiling release binaries via CMake...\n";
        ProcessResult buildRes = ProcessRunner::run("cmake --build build --config Release");
        if (buildRes.exitCode != 0) {
            std::cerr << "  [!] Release build failed. Aborting packaging process.\n\n";
            return buildRes.exitCode;
        }
    } else {
        std::cout << "[1/4] Skipping build phase (--skip-build specified).\n";
    }

    std::cout << "[2/4] Staging release directories...\n";
    try {
        fs::create_directories(releaseDir / "bin");
        fs::create_directories(releaseDir / "include");
    } catch (const std::exception& e) {
        std::cerr << "  [!] Error creating dist structure: " << e.what() << "\n\n";
        return 1;
    }

    std::cout << "[3/4] Copying artifacts and documentation...\n";
    
    // Copy executable if present in build/ or build/Release/
    fs::path exeSrc = "build/forge.exe";
    if (!fs::exists(exeSrc)) exeSrc = "build/Release/forge.exe";
    if (!fs::exists(exeSrc)) exeSrc = "build/forge";

    if (fs::exists(exeSrc)) {
        fs::copy_file(exeSrc, releaseDir / "bin" / exeSrc.filename(), fs::copy_options::overwrite_existing);
        std::cout << "  [+] Staged Binary: " << exeSrc.filename().string() << "\n";
    }

    // Copy primary license and readme
    if (fs::exists("LICENSE")) {
        fs::copy_file("LICENSE", releaseDir / "LICENSE", fs::copy_options::overwrite_existing);
        std::cout << "  [+] Staged: LICENSE\n";
    }
    if (fs::exists("README.md")) {
        fs::copy_file("README.md", releaseDir / "README.md", fs::copy_options::overwrite_existing);
        std::cout << "  [+] Staged: README.md\n";
    }

    std::cout << "[4/4] Generating checksum verification manifest...\n";
    fs::path manifestPath = releaseDir / "SHA256SUMS.txt";
    std::ofstream manifest(manifestPath);
    if (manifest.is_open()) {
        manifest << "# Forge Release Manifest " << version << "\n";
        manifest << "# Auto-generated by forge release\n";
        if (fs::exists(releaseDir / "bin" / exeSrc.filename())) {
            manifest << "bin/" << exeSrc.filename().string() << "\n";
        }
        manifest.close();
        std::cout << "  [+] Created: SHA256SUMS.txt\n";
    }

    std::cout << "\n--------------------------------------------\n";
    std::cout << "  [OK] Release " << version << " packaged successfully at: " << releaseDir.string() << "\n\n";

    return 0;
}

} // namespace forge